---
- name: Install and Initialize Kubernetes Control Plane on Webserver
  hosts: webservers
  become: yes
  vars:
    pod_network_cidr: "10.244.0.0/16"
    cri_socket: "/run/containerd/containerd.sock"
    kubeconfig_dest: "/home/vagrant/.kube/config"

  tasks:
    - name: Disable SELinux temporarily
      command: setenforce 0
      ignore_errors: yes

    - name: Disable SELinux permanently
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*'
        replace: 'SELINUX=permissive'

    - name: Enable required kernel modules
      shell: |
        modprobe br_netfilter
        modprobe overlay

    - name: Ensure kernel modules are loaded at boot
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Set sysctl parameters for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1

    - name: Apply sysctl settings
      command: sysctl --system

    - name: Add Docker CE repo for containerd
      yum_repository:
        name: docker
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/8/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: Install containerd from Docker repo
      dnf:
        name: containerd.io
        state: present

    - name: Configure containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: yes
        state: started

    - name: Install ca-certificates
      dnf:
        name: ca-certificates
        state: present

    - name: Add Kubernetes official repo
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.33/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.33/rpm/repodata/repomd.xml.key
          exclude=kubelet kubeadm kubectl

    - name: Install Kubernetes components
      dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        disable_excludes: kubernetes

    - name: Enable and start kubelet
      systemd:
        name: kubelet
        enabled: yes
        state: started

    - name: Initialize the Kubernetes control plane
      command: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --cri-socket {{ cri_socket }}
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0700

    - name: Copy kubeconfig to user's home
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ kubeconfig_dest }}"
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: 0644

    - name: Install Flannel CNI
      become_user: vagrant
      environment:
        KUBECONFIG: "{{ kubeconfig_dest }}"
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
